NPMRDS data download more robust to abnormal data files.

diff --git a/src/etlPipeline/renameDownloadsUsingContentsFile b/src/etlPipeline/renameDownloadsUsingContentsFile
--- a/src/etlPipeline/renameDownloadsUsingContentsFile
+++ b/src/etlPipeline/renameDownloadsUsingContentsFile
@@ -16,75 +16,80 @@ pushd "$( dirname "${BASH_SOURCE[0]}" )" > /dev/null
 
 source ./datasources
 
-find "$ETL_WORK_DIR" -type f -name "*${INRIX_DOWNLOAD_ZIP_EXTENSION}" |\
-while read -r inf 
-do
-  country_col_num="$(\
-    unzip -p "$inf" TMC_Identification.csv |
-      head -1 |
-      tr ',' '\n' |
-      nl |
-      grep country |
-      sed 's/^[[:blank:]]*//g; s/[[:blank:]].*//g'
-  )"
-
-  countries="$(
-    unzip -p "$inf" TMC_Identification.csv |
-      awk -F, "NR>1{ print tolower(\$${country_col_num}) }" |
-      sort -u
-  )"
-
-  if grep -q 'usa' <<< "$countries"; then
-    # In the RITIS Massive Data Downloader,
-    #   we request data for a US state by specifying that state.
-    # We also get the Canadian border TMCs, so in the TMC_Identification file
-    #   there will be multiple entries in the "state" column.
-    # Therefore, we use the Contents.txt file to guarantee that only a single state
-    #   was requested and determine which state that was.
-
-    # Extract the state name from the contents file
-    state_name="$( unzip -p "$inf" Contents.txt | ./get_state_from_contents_file )"
-  else
-    # In the RITIS Massive Data Downloader,
-    #   we request data for a Canadian provence by specifying the TMCs directly.
-    # There is no "region" option for Canadian provences.
-    # Therefore, we use the TMC_Identificaion file's state column
-    #   to guarantee that only a single state was requested and determine which state that was.
-    state_col_num="$(\
+STATE="$(
+  find "$ETL_WORK_DIR" -type f -name "*${INRIX_DOWNLOAD_ZIP_EXTENSION}" |\
+  while read -r inf
+  do
+    country_col_num="$(\
       unzip -p "$inf" TMC_Identification.csv |
         head -1 |
         tr ',' '\n' |
         nl |
-        grep state |
+        grep country |
         sed 's/^[[:blank:]]*//g; s/[[:blank:]].*//g'
     )"
 
-    # Get rid of diacritics: https://stackoverflow.com/a/10210451
-    state_name="$(
+    countries="$(
       unzip -p "$inf" TMC_Identification.csv |
-        ./stripAccents |
-        awk 'NF' |
-        awk -F, "NR>1{ print tolower(\$${state_col_num}) }" |
+        awk -F, "NR>1{ print tolower(\$${country_col_num}) }" |
         sort -u
     )"
-  fi
 
-  ## RITIS breaks this rule. NY region downloads contain Canadian and New Jersey TMCs.
-  ##   Had to weaken the test to looking only at the Contents file for US states.
-  ##   Canadian provinces are downloaded by requesting specific TMCs.
-  ##     The test is therefore stronger for them.
-  if [ "$(wc -l <<< "$state_name")" -gt 1 ]; then
-    echo 'ERROR: Downloads must contain data for a single state.'
-    echo '       Multiple states listed in TMC_Identification.'
-    exit 1
-  fi
+    if grep -q 'usa' <<< "$countries"; then
+      # In the RITIS Massive Data Downloader,
+      #   we request data for a US state by specifying that state.
+      # We also get the Canadian border TMCs, so in the TMC_Identification file
+      #   there will be multiple entries in the "state" column.
+      # Therefore, we use the Contents.txt file to guarantee that only a single state
+      #   was requested and determine which state that was.
 
-  if [[ "${#state_name}" -eq 2 ]]; then
-    state="${state_name,,}"
-  else
-    state="$( ./stateAbbreviations "$state_name" )"
-  fi
+      # Extract the state name from the contents file
+      state_name="$( unzip -p "$inf" Contents.txt | ./get_state_from_contents_file )"
+    else
+      # In the RITIS Massive Data Downloader,
+      #   we request data for a Canadian provence by specifying the TMCs directly.
+      # There is no "region" option for Canadian provences.
+      # Therefore, we use the TMC_Identificaion file's state column
+      #   to guarantee that only a single state was requested and determine which state that was.
+      state_col_num="$(\
+        unzip -p "$inf" TMC_Identification.csv |
+          head -1 |
+          tr ',' '\n' |
+          nl |
+          grep state |
+          sed 's/^[[:blank:]]*//g; s/[[:blank:]].*//g'
+      )"
 
+      # Get rid of diacritics: https://stackoverflow.com/a/10210451
+      state_name="$(
+        unzip -p "$inf" TMC_Identification.csv |
+          ./stripAccents |
+          awk 'NF' |
+          awk -F, "NR>1{ print tolower(\$${state_col_num}) }" |
+          sort -u
+      )"
+    fi
+
+    if [[ "${#state_name}" -eq 2 ]]; then
+      state="${state_name,,}"
+    else
+      state="$( ./stateAbbreviations "$state_name" )"
+    fi
+
+    echo "$state"
+  done |
+  sort -u
+)"
+
+NL='
+'
+case "$STATE" in
+  *"$NL"*) echo 'ERROR: There is more than one state in the download' && exit 1 ;;
+esac
+
+find "$ETL_WORK_DIR" -type f -name "*${INRIX_DOWNLOAD_ZIP_EXTENSION}" |\
+while read -r inf
+do
   contents="$(unzip -p "$inf" Contents.txt)"
   start_date="$(date -d "$(echo "$contents" | tr '\n' ' ' | sed 's/.*from //g; s/ through.*//g')" '+%Y%m')"
   end_date="$(
